/**
 * NeuralFlow knowledge base.
 *
 * Single source of truth for everything the voice agent can answer from:
 *  - uploaded to Moss (index "neuralflow-kb") by `npm run seed:moss` or at server start
 *  - used by the local keyword index when Moss credentials are not configured
 *
 * Guidelines: one fact or procedure per document, short and self-contained.
 * Short atomic documents retrieve far better than long ones.
 */

export type KnowledgeCategory =
  | 'hardware'
  | 'runbook'
  | 'guardrail'
  | 'incident'
  | 'telemetry'
  | 'reference';

export interface KnowledgeDoc {
  id: string;
  category: KnowledgeCategory;
  title: string;
  summary: string;
  content: string;
  actionableProtocol?: string;
  recommendedAction?: {
    cmd: string;
    params?: Record<string, number | string>;
  };
  keywords: string[];
  tags: string[];
}

export const KNOWLEDGE_BASE: KnowledgeDoc[] = [
  // ── Hardware ─────────────────────────────────────────────────────────────
  {
    id: 'HW-H100-SXM5',
    category: 'hardware',
    title: 'NVIDIA H100 SXM5 Thermal & Power Specifications',
    summary: '700W TDP, 85°C thermal throttle threshold, 90°C critical shutdown limit.',
    content:
      'NVIDIA H100 SXM5 GPU features 80GB HBM3 memory with 3.35TB/s bandwidth and 700W Peak Thermal Design Power (TDP). Thermal throttling automatically triggers at 85°C junction temperature, causing a 30% reduction in streaming multiprocessor (SM) clock frequency. Heat capacity C = 380 J/°C. Newton cooling coefficient k = 3.8 W/°C at baseline airflow.',
    keywords: ['h100', 'nvidia', 'tdp', '700w', '85c', 'temperature', 'specs', 'hardware', 'junction', 'limit', 'throttle'],
    tags: ['hardware', 'nvidia', 'h100'],
  },
  {
    id: 'HW-H200',
    category: 'hardware',
    title: 'NVIDIA H200 Profile',
    summary: 'Hopper generation with 141GB HBM3e, same 700W class TDP as H100 SXM5, so the same cooling runbooks apply.',
    content:
      'The NVIDIA H200 keeps the Hopper architecture and the 700W class thermal envelope of the H100 SXM5 but upgrades memory to 141GB HBM3e. Treat it like an H100 for thermal planning: throttle threshold 85°C, use runbooks RB-01 and RB-04.',
    keywords: ['h200', 'hopper', 'hbm3e', '141gb', 'memory', 'nvidia'],
    tags: ['hardware', 'nvidia', 'h200'],
  },
  {
    id: 'HW-A100',
    category: 'hardware',
    title: 'NVIDIA A100 SXM4 Profile',
    summary: 'Ampere generation, 400W TDP, lower heat density than Hopper.',
    content:
      'The NVIDIA A100 SXM4 (80GB HBM2e) is an Ampere part with a 400W TDP. It produces far less heat per node than an H100, so cooling headroom is larger, but the same predictive pre-ramp approach still removes reactive lag.',
    keywords: ['a100', 'ampere', '400w', 'hbm2e', 'nvidia'],
    tags: ['hardware', 'nvidia', 'a100'],
  },
  {
    id: 'HW-B200-NVL',
    category: 'hardware',
    title: 'NVIDIA B200 NVL Blackwell Next-Gen Profile',
    summary: '1000W TDP dual-die architecture with direct-to-chip liquid cooling coupling.',
    content:
      'NVIDIA Blackwell B200 NVL provides 192GB HBM3e with dual-die design drawing up to 1000W TDP. Requires dynamic predictive coolant flow rate to prevent rapid hotspot formation in transformer matrix multiplication cores. Maximum die delta threshold is 82°C.',
    keywords: ['b200', 'blackwell', '1000w', 'liquid', 'cooling', 'transformer', 'hotspot'],
    tags: ['hardware', 'blackwell', 'b200'],
  },
  {
    id: 'HW-CLUSTER-3X3',
    category: 'hardware',
    title: 'Cluster Topology: 3x3 GPU Rack',
    summary: 'Nine GPUs, GPU-00 to GPU-08, in a 3x3 grid. GPU-04 is the center node and runs hottest.',
    content:
      'The demo cluster is a 3x3 grid of nine GPUs named GPU-00 to GPU-08. The center node GPU-04 is surrounded by eight neighbours and suffers thermal cross-talk, so it runs hottest. Corner nodes GPU-00, GPU-02, GPU-06 and GPU-08 get the best airflow.',
    keywords: ['cluster', 'rack', '3x3', 'gpu-04', 'center', 'topology', 'nine', 'grid', 'layout', 'nodes'],
    tags: ['hardware', 'cluster'],
  },

  // ── Runbooks ─────────────────────────────────────────────────────────────
  {
    id: 'RB-01-BURST',
    category: 'runbook',
    title: 'RB-01: Thermal Runaway & Workload Burst Mitigation',
    summary: 'Pre-ramp cooling fans 30-45s prior to thermal boundary to neutralize thermal inertia.',
    content:
      'When incoming AI inference or fine-tuning traffic exceeds 1,800 req/s, GPU power draw surges from 280W idle to 650W. Reactive PID introduces 15-25s measurement lag. Under RB-01, the system engages proactive fan pre-ramping to 80-85% fan duty cycle to pre-cool the heat sink before silicon temperature reaches 74°C.',
    actionableProtocol: 'Pre-ramp fan speed to 80% immediately and engage the predictive horizon.',
    recommendedAction: { cmd: 'preramp', params: { fanTarget: 80, mode: 'pinn' } },
    keywords: ['burst', 'spike', 'inference', 'runaway', 'preramp', 'fans', 'overheating', 'hot', 'cooling', 'lag', 'traffic'],
    tags: ['runbook', 'mitigation'],
  },
  {
    id: 'RB-01-TRIGGER',
    category: 'runbook',
    title: 'RB-01 Trigger Conditions',
    summary: 'Invoke RB-01 when traffic passes 1,800 requests per second or the forecast crosses 74°C.',
    content:
      'RB-01 is triggered by either of two conditions: incoming request rate above 1,800 req/s, or the 60-second forecast for junction temperature passing 74°C. Either condition means fans should start pre-ramping now, not after the temperature rises.',
    keywords: ['trigger', 'when', 'condition', 'threshold', '1800', '74c', 'forecast'],
    tags: ['runbook', 'trigger'],
  },
  {
    id: 'RB-02-PID-OSCILLATION',
    category: 'runbook',
    title: 'RB-02: PID Integral Windup & Overcooling Mitigation',
    summary: 'Mitigate PID overshoot and excessive fan power consumption after power drop.',
    content:
      'Traditional PID controllers experience integral windup during sustained high-load events, causing fans to run at 100% long after workload has terminated. This degrades PUE and wastes cooling energy. Protocol: disengage the PID integral accumulator and switch to the NeuralFlow physics-informed controller.',
    actionableProtocol: 'Switch controller to NeuralFlow mode and reset the PID accumulator.',
    recommendedAction: { cmd: 'switch_pinn', params: { mode: 'pinn' } },
    keywords: ['pid', 'windup', 'overshoot', 'overcooling', 'waste', 'energy', 'oscillation', 'pue'],
    tags: ['runbook', 'efficiency'],
  },
  {
    id: 'RB-03-CLUSTER-BALANCE',
    category: 'runbook',
    title: 'RB-03: 3x3 Cluster Workload & Thermal Re-balancing',
    summary: 'Disperse hotspot concentrations across GPU-00 through GPU-08.',
    content:
      'In a 9-node GPU cluster, center nodes (e.g. GPU-04) suffer from thermal cross-talk from neighboring nodes. RB-03 redistributes active batch training chunks to perimeter nodes (GPU-00, GPU-02, GPU-06, GPU-08) where airflow velocity is 18% higher.',
    actionableProtocol: 'Distribute batch jobs to exterior perimeter GPUs and set center fan to 75%.',
    recommendedAction: { cmd: 'rebalance', params: { targetFan: 75, balanceFactor: 0.85 } },
    keywords: ['cluster', 'rack', '3x3', 'rebalance', 'hotspot', 'gpu-04', 'airflow', 'thermal', 'distribution'],
    tags: ['runbook', 'cluster'],
  },
  {
    id: 'RB-04-EMERGENCY-TRIP',
    category: 'guardrail',
    title: 'RB-04: Critical 85°C Throttling Prevention Guardrail',
    summary: 'Safety override to avoid hardware degradation and clock frequency drop.',
    content:
      'If forecasted junction temperature exceeds 82°C within 15 seconds with forecast uncertainty above 2.0°C, the safety guardrail overrides manual throttles, forces fan speed to 100%, and throttles background batch jobs to prevent hardware throttling (85°C limit).',
    actionableProtocol: 'Safety override: force maximum fan speed (100%) and damp the batch queue.',
    recommendedAction: { cmd: 'emergency_fan', params: { fanTarget: 100, batchDamp: 0.3 } },
    keywords: ['emergency', 'critical', '85c', 'throttle', 'trip', 'guardrail', 'safety', 'shutdown', 'protection'],
    tags: ['guardrail', 'safety'],
  },
  {
    id: 'RB-05-RECOVERY',
    category: 'runbook',
    title: 'RB-05: Post-Event Recovery',
    summary: 'After an emergency, step fans down gradually and return to the predictive controller.',
    content:
      'After RB-04 fires, do not drop fans straight from 100%. Step the fan target down in increments while the forecast stays below 74°C, release the batch queue damping, and return control to the predictive controller. Sudden fan drops cause a second temperature spike.',
    actionableProtocol: 'Reduce fans in steps while the forecast stays under 74°C, then release batch damping.',
    keywords: ['recovery', 'after', 'emergency', 'step', 'down', 'release', 'normal', 'resume'],
    tags: ['runbook', 'recovery'],
  },

  // ── Guardrails ───────────────────────────────────────────────────────────
  {
    id: 'GD-THRESHOLDS',
    category: 'guardrail',
    title: 'GD-02: Temperature Thresholds',
    summary: '74°C start pre-cooling, 82°C forecast triggers the override, 85°C GPU throttles, 90°C critical shutdown.',
    content:
      'Operating thresholds for junction temperature: 74°C is the pre-cooling zone where fans should already be ramping. A forecast above 82°C triggers the RB-04 override. At 85°C the GPU throttles its clocks by about 30%. At 90°C the hardware performs a critical shutdown.',
    keywords: ['threshold', 'thresholds', 'limits', 'temperature', '74', '82', '85', '90', 'levels', 'safe'],
    tags: ['guardrail', 'thresholds'],
  },
  {
    id: 'GD-LATENCY-SLA',
    category: 'guardrail',
    title: 'GD-01: Real-Time Voice Latency Budget',
    summary: 'Voice agent context retrieval must be fast enough to stay out of the latency budget, under 10 milliseconds with Moss.',
    content:
      'Live voice dispatch needs the conversation to feel instant. A remote vector database adds a network round trip of hundreds of milliseconds per lookup, which breaks real-time speech. Moss runs retrieval inside the agent process after the index is loaded, so lookups take single-digit milliseconds.',
    keywords: ['latency', 'sla', 'speed', 'moss', 'retrieval', 'voice', 'livekit', 'fast', 'realtime', 'vector'],
    tags: ['guardrail', 'voice', 'moss'],
  },
  {
    id: 'GD-CONFIRM',
    category: 'guardrail',
    title: 'GD-03: Voice Command Safety',
    summary: 'Fan speed is clamped between 20 and 100 percent, and the emergency guardrail cannot be disabled by voice.',
    content:
      'Voice commands can adjust fan speed only within 20 to 100 percent. The RB-04 emergency guardrail cannot be turned off by voice. The operator can always say pause or reset to stop the simulation.',
    keywords: ['voice', 'command', 'safety', 'clamp', 'limit', 'fan', 'permission', 'allowed'],
    tags: ['guardrail', 'voice'],
  },

  // ── Incidents ────────────────────────────────────────────────────────────
  {
    id: 'INC-2026-08',
    category: 'incident',
    title: 'Historical Incident Report: Cluster Thermal Spike during LLaMA-3 Batch Run',
    summary: 'Reactive PID delay caused 7 thermal throttle events; resolved with proactive feed-forward.',
    content:
      'During an unattended overnight batch run, a sudden queue of 2,400 concurrent inference requests caused peak GPU temperature to spike to 84.2°C under PID control. The NeuralFlow replica remained under 71°C by pre-ramping fans 30s ahead, preventing 7 throttle incidents and saving 12.8% cooling energy.',
    keywords: ['incident', 'history', 'llama', 'spike', '84c', 'throttle', 'batch', 'lesson', 'comparison'],
    tags: ['incident', 'history'],
  },
  {
    id: 'INC-LESSONS',
    category: 'incident',
    title: 'Incident Lesson: Why Reactive Cooling Fails',
    summary: 'Silicon heats in seconds but fans respond to a lagging sensor, so reactive control is always late.',
    content:
      'The core lesson from thermal incidents: GPU junction temperature rises within seconds of a load spike, while a reactive controller only sees the rise after sensor lag and then needs time to spin fans up. Acting on the forecast instead of the current reading closes that gap.',
    keywords: ['lesson', 'why', 'reactive', 'late', 'lag', 'sensor', 'fails', 'problem'],
    tags: ['incident', 'lesson'],
  },

  // ── Reference / glossary ─────────────────────────────────────────────────
  {
    id: 'REF-FORECAST',
    category: 'reference',
    title: 'How the Predictive Forecast Works',
    summary: 'A physics model projects junction temperature 30, 45 and 60 seconds ahead using Newton cooling and recent power trend.',
    content:
      'NeuralFlow forecasts junction temperature at 30, 45 and 60 seconds ahead by integrating the thermal equation dT/dt = P/C - k(T - ambient), where P is recent GPU power, C is heat capacity and k depends on fan speed. Forecast uncertainty grows with the horizon and with power volatility.',
    keywords: ['forecast', 'predict', 'horizon', 'prediction', 'physics', 'newton', 'model', 'how', 'works', 'pinn', 'uncertainty', 'ahead'],
    tags: ['reference', 'forecast'],
  },
  {
    id: 'REF-THERMAL-INERTIA',
    category: 'reference',
    title: 'Glossary: Thermal Inertia',
    summary: 'Thermal inertia is how long heat sinks and coolant take to respond, which is why cooling must start early.',
    content:
      'Thermal inertia is the delay between changing fan speed and seeing the temperature respond, caused by the heat capacity of the GPU package and heat sink. Because of it, fans started after a spike cannot stop the spike, they can only limit it.',
    keywords: ['thermal', 'inertia', 'delay', 'heat', 'capacity', 'glossary', 'meaning', 'define'],
    tags: ['reference', 'glossary'],
  },
  {
    id: 'REF-THROTTLING',
    category: 'reference',
    title: 'Glossary: Thermal Throttling',
    summary: 'Throttling is the GPU cutting its own clock speed to protect itself, which slows every job on it.',
    content:
      'Thermal throttling happens when the GPU junction reaches its limit, 85°C for an H100, and hardware reduces clock frequency to shed heat. Throughput drops and latency rises, so avoiding throttling is worth more than the energy spent on extra cooling.',
    keywords: ['throttling', 'throttle', 'clock', 'slow', 'performance', 'glossary', 'meaning', 'define', 'what'],
    tags: ['reference', 'glossary'],
  },
  {
    id: 'REF-PUE',
    category: 'reference',
    title: 'Glossary: PUE and Cooling Energy',
    summary: 'PUE is total facility power divided by IT power; wasted fan power raises it.',
    content:
      'Power Usage Effectiveness (PUE) is total facility energy divided by IT equipment energy. Fans running at high speed when they are not needed add cooling energy and push PUE up. Fan power grows roughly with the cube of fan speed, so small reductions save a lot.',
    keywords: ['pue', 'power', 'usage', 'effectiveness', 'energy', 'efficiency', 'fan', 'cube', 'glossary', 'saving'],
    tags: ['reference', 'glossary', 'energy'],
  },
  {
    id: 'REF-PID-VS-NF',
    category: 'reference',
    title: 'Benchmark: Reactive PID vs NeuralFlow (10-minute simulation)',
    summary: 'In simulation, peak temperature falls from 84°C to 71°C, throttle events from 7 to 0, and cooling energy drops 12.8%.',
    content:
      'Simulation benchmark over a 10-minute mixed workload: reactive PID peaked at 84°C with 7 throttle events and used 148 Wh of cooling energy. NeuralFlow peaked at 71°C with 0 throttle events and used 129 Wh, a 12.8% saving. These figures come from the built-in simulator, not from real hardware.',
    keywords: ['benchmark', 'compare', 'comparison', 'pid', 'neuralflow', 'results', 'saving', 'peak', 'energy', 'versus', 'better'],
    tags: ['reference', 'benchmark'],
  },
  {
    id: 'REF-WORKLOADS',
    category: 'reference',
    title: 'Workload Levels in the Simulator',
    summary: 'AI requests per second drive GPU power; above about 1,800 requests per second the cluster enters the burst regime.',
    content:
      'The simulator models load as AI inference requests per second plus API requests and users. Power rises with request rate, from about 280W idle to about 650W under burst. Saying increase workload raises AI requests so you can watch the forecast react.',
    keywords: ['workload', 'load', 'requests', 'traffic', 'users', 'simulator', 'increase', 'burst', 'power'],
    tags: ['reference', 'simulator'],
  },
  {
    id: 'REF-VOICE-HOWTO',
    category: 'reference',
    title: 'Voice Commands You Can Use',
    summary: 'Say start simulation, increase workload, pre-ramp fans, rebalance cluster, emergency cooling, reset, or ask about specs and runbooks.',
    content:
      'Action commands: start simulation, pause, reset, increase workload, decrease workload, increase fan speed, pre-ramp fans, rebalance cluster, emergency cooling. Question examples: what are the H100 specs, what does RB-01 say, when do I trigger the emergency guardrail, how does the forecast work, compare PID and NeuralFlow.',
    keywords: ['commands', 'help', 'say', 'voice', 'how', 'use', 'options', 'examples', 'what can'],
    tags: ['reference', 'voice'],
  },
  {
    id: 'REF-FAN-POWER',
    category: 'reference',
    title: 'Fan Speed and Power',
    summary: 'Fan power rises roughly with the cube of speed, so 100% fans cost about eight times the power of 50%.',
    content:
      'Fan affinity laws say fan power scales roughly with the cube of speed. Running fans at 100% instead of 50% costs about eight times the power. That is why holding fans high after a spike wastes energy, and why pre-ramping to about 80% just in time is more efficient than pinning them at maximum.',
    keywords: ['fan', 'power', 'cube', 'affinity', 'speed', 'energy', 'cost', 'watts', 'efficiency'],
    tags: ['reference', 'energy'],
  },

  // ── Expansion: 72 synthetic + curated docs (2026-09-22) ───────────────
  {
    id: 'HW-RACK-AIRFLOW-01',
    category: 'hardware',
    title: 'Rack Airflow Baseline',
    summary: 'The 3×3 NeuralFlow rack has strongest airflow at perimeter positions.',
    content: 'The 3×3 NeuralFlow rack has strongest airflow at perimeter positions. During sustained bursts, interior GPUs can accumulate heat faster, so workload balancing should consider airflow position as well as temperature.',
    keywords: ['rack', 'airflow', 'perimeter', '3x3', 'baseline', 'hw', '01', 'neuralflow', 'strongest', 'positions'],
    tags: ['rack', 'airflow', 'perimeter', '3x3', 'hardware'],
  },
  {
    id: 'HW-GPU04-POSITION',
    category: 'hardware',
    title: 'GPU-04 Thermal Position',
    summary: 'GPU-04 is the recurring thermal hotspot in the reference 3×3 cluster.',
    content: 'GPU-04 is the recurring thermal hotspot in the reference 3×3 cluster. When it rises faster than neighbors, investigate workload placement and local airflow before simply increasing every fan.',
    keywords: ['gpu-04', 'hotspot', 'cluster', 'airflow', 'gpu', 'thermal', 'position', 'hw', 'gpu04', 'recurring'],
    tags: ['gpu-04', 'hotspot', 'cluster', 'airflow', 'hardware'],
  },
  {
    id: 'HW-H100-THERMAL',
    category: 'hardware',
    title: 'H100-SXM5 Thermal Envelope',
    summary: 'The NeuralFlow reference profile records 700 W TDP for the H100-SXM5 and uses 85°C as the throttling threshold in the...',
    content: 'The NeuralFlow reference profile records 700 W TDP for the H100-SXM5 and uses 85°C as the throttling threshold in the simulated control policy.',
    keywords: ['h100', '700w', '85c', 'throttle', 'sxm5', 'thermal', 'envelope', 'hw', 'neuralflow', 'reference'],
    tags: ['h100', '700w', '85c', 'throttle', 'hardware'],
  },
  {
    id: 'HW-H200-THERMAL',
    category: 'hardware',
    title: 'H200 Thermal Envelope',
    summary: 'The NeuralFlow reference profile treats the H200 with the same 85°C thermal throttle boundary used by the reference...',
    content: 'The NeuralFlow reference profile treats the H200 with the same 85°C thermal throttle boundary used by the reference control policy and models it as a high-power accelerator requiring proactive cooling under sustained load.',
    keywords: ['h200', '85c', 'proactive cooling', 'thermal', 'envelope', 'hw', 'neuralflow', 'reference', 'profile', 'treats'],
    tags: ['h200', '85c', 'proactive cooling', 'hardware'],
  },
  {
    id: 'HW-A100-THERMAL',
    category: 'hardware',
    title: 'A100 Reference Profile',
    summary: 'The A100 reference profile uses 400 W TDP in the simulator.',
    content: 'The A100 reference profile uses 400 W TDP in the simulator. It is modeled as a lower-power accelerator than the H100/H200 profiles but still benefits from early cooling when the predicted trajectory is rising.',
    keywords: ['a100', '400w', 'forecast', 'reference', 'profile', 'hw', 'thermal', 'uses', 'simulator', 'modeled'],
    tags: ['a100', '400w', 'forecast', 'hardware'],
  },
  {
    id: 'HW-B200-NVL-LIQUID',
    category: 'hardware',
    title: 'B200-NVL Reference Profile',
    summary: 'The NeuralFlow reference profile models the B200-NVL at 1000 W and assumes liquid-cooling support.',
    content: 'The NeuralFlow reference profile models the B200-NVL at 1000 W and assumes liquid-cooling support. Its control profile uses an 82°C maximum die-delta guardrail before emergency override behavior.',
    keywords: ['b200', '1000w', 'liquid cooling', '82c', 'nvl', 'reference', 'profile', 'hw', 'neuralflow', 'models'],
    tags: ['b200', '1000w', 'liquid cooling', '82c', 'hardware'],
  },
  {
    id: 'HW-CLUSTER-3X3-EDGE',
    category: 'hardware',
    title: '3×3 Edge GPU Behavior',
    summary: 'Perimeter GPUs in the 3×3 cluster generally have better airflow access than interior positions.',
    content: 'Perimeter GPUs in the 3×3 cluster generally have better airflow access than interior positions. During a rising thermal gradient, moving suitable workload toward cooler perimeter nodes can reduce localized heat concentration.',
    keywords: ['3x3', 'perimeter', 'workload placement', 'edge', 'gpu', 'behavior', 'hw', 'cluster', 'gpus', 'generally'],
    tags: ['3x3', 'perimeter', 'workload placement', 'hardware'],
  },
  {
    id: 'HW-FAN-CUBE-LAW',
    category: 'hardware',
    title: 'Fan Power Relationship',
    summary: 'The reference model uses a fan-power relationship that grows approximately with the cube of fan speed.',
    content: 'The reference model uses a fan-power relationship that grows approximately with the cube of fan speed. This makes prolonged high-speed fan operation disproportionately expensive compared with moderate proactive cooling.',
    keywords: ['fan power', 'cube law', 'energy', 'fan', 'power', 'relationship', 'hw', 'cube', 'law', 'reference'],
    tags: ['fan power', 'cube law', 'energy', 'hardware'],
  },
  {
    id: 'HW-THERMAL-INERTIA',
    category: 'hardware',
    title: 'Thermal Inertia Reference',
    summary: 'Heat sinks and coolant do not react instantaneously to a change in GPU power.',
    content: 'Heat sinks and coolant do not react instantaneously to a change in GPU power. The control model therefore treats temperature as a delayed physical response and values early intervention based on predicted heat rather than only current measurements.',
    keywords: ['thermal inertia', 'forecast', 'cooling', 'thermal', 'inertia', 'reference', 'hw', 'heat', 'sinks', 'coolant'],
    tags: ['thermal inertia', 'forecast', 'cooling', 'hardware'],
  },
  {
    id: 'HW-POWER-WORKLOAD',
    category: 'hardware',
    title: 'Workload-to-Power Mapping',
    summary: 'The reference simulator maps AI request rate and workload intensity to GPU power.',
    content: 'The reference simulator maps AI request rate and workload intensity to GPU power. In the baseline model, power rises from roughly 280 W at idle toward about 650 W under burst conditions.',
    keywords: ['workload', 'power', '650w', '280w', 'mapping', 'hw', 'reference', 'simulator', 'maps', 'request'],
    tags: ['workload', 'power', '650w', '280w', 'hardware'],
  },
  {
    id: 'HW-SENSOR-LAG',
    category: 'hardware',
    title: 'Sensor Response Profile',
    summary: 'The reference simulation assumes that sensor-driven reactive control can observe a rapidly rising thermal state only...',
    content: 'The reference simulation assumes that sensor-driven reactive control can observe a rapidly rising thermal state only after some physical and measurement delay. This lag is one reason predictive control starts cooling earlier.',
    keywords: ['sensor lag', 'thermal response', 'reactive', 'sensor', 'response', 'profile', 'hw', 'lag', 'reference', 'simulation'],
    tags: ['sensor lag', 'thermal response', 'reactive', 'hardware'],
  },
  {
    id: 'HW-COOLING-HEADROOM',
    category: 'hardware',
    title: 'Cooling Headroom Concept',
    summary: 'Cooling headroom is the gap between current thermal state and the temperature at which stronger protective action...',
    content: 'Cooling headroom is the gap between current thermal state and the temperature at which stronger protective action becomes necessary. NeuralFlow preserves headroom by responding to forecasted risk before the system reaches the hard limit.',
    keywords: ['headroom', 'thermal margin', 'forecast', 'cooling', 'concept', 'hw', 'between', 'current', 'thermal', 'state'],
    tags: ['headroom', 'thermal margin', 'forecast', 'hardware'],
  },
  {
    id: 'RB-06-PREEMPTIVE-COOLING',
    category: 'runbook',
    title: 'Preemptive Cooling Before a Rapid Rise',
    summary: 'When the forecast indicates temperature is rising quickly, increase cooling before the measured temperature enters the...',
    content: 'When the forecast indicates temperature is rising quickly, increase cooling before the measured temperature enters the throttle zone. The purpose is to absorb thermal inertia and prevent the system from arriving at the limit with no remaining control margin.',
    keywords: ['preemptive', 'cooling', 'forecast', 'thermal inertia', 'before', 'rapid', 'rise', 'rb', '06', 'indicates'],
    tags: ['preemptive', 'cooling', 'forecast', 'thermal inertia', 'runbook'],
  },
  {
    id: 'RB-07-HOTSPOT-CONTAINMENT',
    category: 'runbook',
    title: 'Hotspot Containment',
    summary: 'If one GPU becomes noticeably hotter than its peers, identify whether the cause is workload concentration or airflow...',
    content: 'If one GPU becomes noticeably hotter than its peers, identify whether the cause is workload concentration or airflow asymmetry. Contain the hotspot with targeted fan response and, where policy allows, shift workload toward cooler perimeter GPUs.',
    keywords: ['hotspot', 'gpu', 'workload shift', 'airflow', 'containment', 'rb', '07', 'becomes', 'noticeably', 'hotter'],
    tags: ['hotspot', 'gpu', 'workload shift', 'airflow', 'runbook'],
  },
  {
    id: 'RB-08-GRADUAL-RECOVERY',
    category: 'runbook',
    title: 'Gradual Recovery After a Burst',
    summary: 'After a high-load interval ends, reduce fan speed in controlled steps rather than returning immediately to baseline.',
    content: 'After a high-load interval ends, reduce fan speed in controlled steps rather than returning immediately to baseline. This avoids a thermal rebound caused by stored heat in the heatsink and coolant path.',
    keywords: ['recovery', 'fan', 'thermal rebound', 'gradual', 'after', 'burst', 'rb', '08', 'high-load', 'interval'],
    tags: ['recovery', 'fan', 'thermal rebound', 'runbook'],
  },
  {
    id: 'RB-09-PID-WINDUP-CHECK',
    category: 'runbook',
    title: 'PID Windup Investigation',
    summary: 'When reactive PID keeps fans elevated after a thermal event has passed, inspect integral windup and delayed feedback.',
    content: 'When reactive PID keeps fans elevated after a thermal event has passed, inspect integral windup and delayed feedback. Avoid compensating for lag with excessive sustained actuation.',
    keywords: ['pid', 'windup', 'feedback', 'overcooling', 'investigation', 'rb', '09', 'check', 'reactive', 'keeps'],
    tags: ['pid', 'windup', 'feedback', 'overcooling', 'runbook'],
  },
  {
    id: 'RB-10-CLUSTER-REDISTRIBUTION',
    category: 'runbook',
    title: 'Cluster Workload Redistribution',
    summary: 'When a single GPU is persistently hotter than adjacent nodes, redistribute suitable workload toward cooler cluster...',
    content: 'When a single GPU is persistently hotter than adjacent nodes, redistribute suitable workload toward cooler cluster positions instead of forcing every fan to maximum speed.',
    keywords: ['cluster', 'redistribution', 'gpu-04', 'workload', 'rb', '10', 'single', 'persistently', 'hotter', 'than'],
    tags: ['cluster', 'redistribution', 'gpu-04', 'workload', 'runbook'],
  },
  {
    id: 'RB-11-FORECAST-CHECK',
    category: 'runbook',
    title: 'Forecast Validation Before Escalation',
    summary: 'Before escalating cooling aggressively, check whether the predicted trajectory remains above the relevant threshold...',
    content: 'Before escalating cooling aggressively, check whether the predicted trajectory remains above the relevant threshold across multiple forecast points. A single noisy prediction should not cause repeated large control changes.',
    keywords: ['forecast', 'validation', 'noise', 'control', 'before', 'escalation', 'rb', '11', 'check', 'escalating'],
    tags: ['forecast', 'validation', 'noise', 'control', 'runbook'],
  },
  {
    id: 'RB-12-BURST-ENTRY',
    category: 'runbook',
    title: 'Burst Entry Procedure',
    summary: 'When a high-demand workload is about to begin, establish cooling headroom before the power ramp.',
    content: 'When a high-demand workload is about to begin, establish cooling headroom before the power ramp. Pre-ramping fans is preferred to waiting for temperature to cross a threshold after the workload is already active.',
    keywords: ['burst', 'pre-ramp', 'headroom', 'entry', 'procedure', 'rb', '12', 'high-demand', 'workload', 'about'],
    tags: ['burst', 'pre-ramp', 'headroom', 'runbook'],
  },
  {
    id: 'RB-13-BURST-EXIT',
    category: 'runbook',
    title: 'Burst Exit Procedure',
    summary: 'When a burst completes, hold the cooling state briefly and then step fans down gradually.',
    content: 'When a burst completes, hold the cooling state briefly and then step fans down gradually. Confirm that predicted temperature is stabilizing before returning to baseline fan speed.',
    keywords: ['burst', 'exit', 'fan', 'recovery', 'procedure', 'rb', '13', 'completes', 'hold', 'cooling'],
    tags: ['burst', 'exit', 'fan', 'recovery', 'runbook'],
  },
  {
    id: 'RB-14-FORECAST-OVERRIDE',
    category: 'runbook',
    title: 'Forecast-Based Override Procedure',
    summary: 'If the forecast crosses the emergency override level, bypass normal gradual cooling behavior and apply the emergency...',
    content: 'If the forecast crosses the emergency override level, bypass normal gradual cooling behavior and apply the emergency control policy. The forecast can trigger protective action before physical temperature reaches the same level.',
    keywords: ['override', 'forecast', 'emergency', 'based', 'procedure', 'rb', '14', 'crosses', 'level', 'bypass'],
    tags: ['override', 'forecast', 'emergency', 'runbook'],
  },
  {
    id: 'RB-15-VOICE-SAFE-CONTROL',
    category: 'runbook',
    title: 'Voice Control Safety Procedure',
    summary: 'Voice commands may request fan changes within the allowed range, but emergency protection cannot be disabled by voice.',
    content: 'Voice commands may request fan changes within the allowed range, but emergency protection cannot be disabled by voice. Safety guardrails remain authoritative over operator convenience.',
    keywords: ['voice', 'safety', 'fan', 'guardrails', 'control', 'procedure', 'rb', '15', 'safe', 'commands'],
    tags: ['voice', 'safety', 'fan', 'guardrails', 'runbook'],
  },
  {
    id: 'RB-16-RECHECK-AFTER-ACTION',
    category: 'runbook',
    title: 'Post-Action Verification',
    summary: 'After any cooling or workload control action, re-check temperature, fan speed, workload, and forecast.',
    content: 'After any cooling or workload control action, re-check temperature, fan speed, workload, and forecast. The action is successful only if the thermal trajectory responds as intended.',
    keywords: ['verification', 'telemetry', 'forecast', 'post', 'action', 'rb', '16', 'recheck', 'after', 'cooling'],
    tags: ['verification', 'telemetry', 'forecast', 'runbook'],
  },
  {
    id: 'RB-17-SUSTAINED-LOAD',
    category: 'runbook',
    title: 'Sustained High-Load Procedure',
    summary: 'For workloads that remain elevated for several minutes, favor stable fan control and workload distribution rather than...',
    content: 'For workloads that remain elevated for several minutes, favor stable fan control and workload distribution rather than repeated rapid changes. Continuous oscillation can waste energy without improving thermal stability.',
    keywords: ['sustained load', 'oscillation', 'energy', 'sustained', 'high', 'load', 'procedure', 'rb', '17', 'workloads'],
    tags: ['sustained load', 'oscillation', 'energy', 'runbook'],
  },
  {
    id: 'RB-18-SENSOR-MISMATCH',
    category: 'runbook',
    title: 'Sensor Mismatch Investigation',
    summary: 'If sensor readings disagree with the expected thermal trajectory, compare neighboring GPU sensors and recent workload...',
    content: 'If sensor readings disagree with the expected thermal trajectory, compare neighboring GPU sensors and recent workload changes. Do not automatically assume the hottest value is a hardware failure without corroboration.',
    keywords: ['sensor', 'mismatch', 'diagnostic', 'investigation', 'rb', '18', 'readings', 'disagree', 'expected', 'thermal'],
    tags: ['sensor', 'mismatch', 'diagnostic', 'runbook'],
  },
  {
    id: 'RB-19-LOW-AIRFLOW',
    category: 'runbook',
    title: 'Low Airflow Investigation',
    summary: 'When temperature rises without a proportional workload increase, inspect airflow distribution and local fan behavior.',
    content: 'When temperature rises without a proportional workload increase, inspect airflow distribution and local fan behavior. A localized airflow restriction can create a hotspot even when cluster-wide power is stable.',
    keywords: ['airflow', 'hotspot', 'diagnostic', 'low', 'investigation', 'rb', '19', 'temperature', 'rises', 'without'],
    tags: ['airflow', 'hotspot', 'diagnostic', 'runbook'],
  },
  {
    id: 'RB-20-ENERGY-AWARE-COOLING',
    category: 'runbook',
    title: 'Energy-Aware Cooling Procedure',
    summary: 'When thermal risk is low and the forecast is stable, avoid unnecessary maximum fan speed.',
    content: 'When thermal risk is low and the forecast is stable, avoid unnecessary maximum fan speed. The objective is to maintain safe thermal margins while minimizing avoidable fan power.',
    keywords: ['energy', 'cooling', 'efficiency', 'aware', 'procedure', 'rb', '20', 'thermal', 'risk', 'forecast'],
    tags: ['energy', 'cooling', 'efficiency', 'runbook'],
  },
  {
    id: 'RB-21-POST-THROTTLE-RECOVERY',
    category: 'runbook',
    title: 'Post-Throttle Recovery',
    summary: 'After a throttle event, record the trigger condition, peak temperature, workload state, and cooling response.',
    content: 'After a throttle event, record the trigger condition, peak temperature, workload state, and cooling response. Use the incident data to determine whether intervention should begin earlier on subsequent runs.',
    keywords: ['throttle', 'recovery', 'incident', 'learning', 'post', 'rb', '21', 'after', 'event', 'record'],
    tags: ['throttle', 'recovery', 'incident', 'learning', 'runbook'],
  },
  {
    id: 'GD-03-FAN-RANGE',
    category: 'guardrail',
    title: 'Voice Fan Command Range',
    summary: 'Voice-requested fan speeds are clamped to the permitted operating range of 20–100%.',
    content: 'Voice-requested fan speeds are clamped to the permitted operating range of 20–100%. The safety controller remains authoritative if a requested value conflicts with emergency policy.',
    keywords: ['fan', 'voice', '20%', '100%', 'command', 'range', 'gd', '03', 'voice-requested', 'speeds'],
    tags: ['fan', 'voice', '20%', '100%', 'guardrail'],
  },
  {
    id: 'GD-04-PRECOOL',
    category: 'guardrail',
    title: 'Pre-Cool Threshold',
    summary: 'The reference NeuralFlow policy begins proactive cooling at 74°C or when the forecast indicates that the 60-second...',
    content: 'The reference NeuralFlow policy begins proactive cooling at 74°C or when the forecast indicates that the 60-second horizon will cross the pre-cool threshold.',
    keywords: ['74c', 'pre-cool', 'forecast', 'pre', 'cool', 'threshold', 'gd', '04', 'precool', 'reference'],
    tags: ['74c', 'pre-cool', 'forecast', 'guardrail'],
  },
  {
    id: 'GD-05-OVERRIDE',
    category: 'guardrail',
    title: 'Thermal Override Threshold',
    summary: 'An 82°C forecast or measured control condition triggers stronger override behavior in the reference policy, before the...',
    content: 'An 82°C forecast or measured control condition triggers stronger override behavior in the reference policy, before the 85°C throttle point.',
    keywords: ['82c', 'override', 'protection', 'thermal', 'threshold', 'gd', '05', 'forecast', 'measured', 'control'],
    tags: ['82c', 'override', 'protection', 'guardrail'],
  },
  {
    id: 'GD-06-THROTTLE',
    category: 'guardrail',
    title: 'Throttle Threshold',
    summary: 'The reference control policy treats 85°C as the thermal point associated with GPU throttling.',
    content: 'The reference control policy treats 85°C as the thermal point associated with GPU throttling.',
    keywords: ['85c', 'throttle', 'threshold', 'gd', '06', 'reference', 'control', 'policy', 'treats', 'thermal'],
    tags: ['85c', 'throttle', 'guardrail'],
  },
  {
    id: 'GD-07-SHUTDOWN',
    category: 'guardrail',
    title: 'Critical Shutdown Threshold',
    summary: 'The reference control policy uses 90°C as the critical shutdown threshold for the simulated environment.',
    content: 'The reference control policy uses 90°C as the critical shutdown threshold for the simulated environment.',
    keywords: ['90c', 'shutdown', 'critical', 'threshold', 'gd', '07', 'reference', 'control', 'policy', 'uses'],
    tags: ['90c', 'shutdown', 'critical', 'guardrail'],
  },
  {
    id: 'GD-08-FORECAST-CONFIDENCE',
    category: 'guardrail',
    title: 'Forecast Confidence Guardrail',
    summary: 'Control escalation should consider prediction confidence.',
    content: 'Control escalation should consider prediction confidence. When uncertainty is unusually high, inspect recent trajectory and supporting telemetry instead of blindly escalating every response.',
    keywords: ['uncertainty', 'confidence', 'forecast', 'guardrail', 'gd', '08', 'control', 'escalation', 'consider', 'prediction'],
    tags: ['uncertainty', 'confidence', 'forecast', 'guardrail'],
  },
  {
    id: 'GD-09-EMERGENCY-NO-DISABLE',
    category: 'guardrail',
    title: 'Emergency Protection Cannot Be Disabled by Voice',
    summary: 'A voice instruction cannot disable emergency thermal protection.',
    content: 'A voice instruction cannot disable emergency thermal protection. Operational requests remain subordinate to controller safety limits.',
    keywords: ['voice', 'emergency', 'safety', 'protection', 'cannot', 'disabled', 'gd', '09', 'no', 'disable'],
    tags: ['voice', 'emergency', 'safety', 'guardrail'],
  },
  {
    id: 'GD-10-RATE-LIMIT',
    category: 'guardrail',
    title: 'Control Change Rate Limit',
    summary: 'Avoid rapid repeated control changes when measured and forecast temperatures are stable.',
    content: 'Avoid rapid repeated control changes when measured and forecast temperatures are stable. Rate limiting reduces actuator chatter and makes thermal control easier to audit.',
    keywords: ['rate limit', 'control', 'oscillation', 'change', 'rate', 'limit', 'gd', '10', 'avoid', 'rapid'],
    tags: ['rate limit', 'control', 'oscillation', 'guardrail'],
  },
  {
    id: 'GD-11-CLUSTER-SAFETY',
    category: 'guardrail',
    title: 'Cluster-Wide Safety Precedence',
    summary: 'Cluster-level protective rules take precedence over local optimization.',
    content: 'Cluster-level protective rules take precedence over local optimization. A cool GPU cannot justify an action that causes another GPU to cross a safety threshold.',
    keywords: ['cluster', 'safety', 'precedence', 'wide', 'gd', '11', 'cluster-level', 'protective', 'rules', 'take'],
    tags: ['cluster', 'safety', 'precedence', 'guardrail'],
  },
  {
    id: 'GD-12-AUDIT',
    category: 'guardrail',
    title: 'Control Audit Requirement',
    summary: 'Every automated or voice-triggered control action should retain its command, timestamp, resulting state, and retrieval...',
    content: 'Every automated or voice-triggered control action should retain its command, timestamp, resulting state, and retrieval or decision context so operators can reconstruct why the system acted.',
    keywords: ['audit', 'control', 'traceability', 'requirement', 'gd', '12', 'every', 'automated', 'voice-triggered', 'action'],
    tags: ['audit', 'control', 'traceability', 'guardrail'],
  },
  {
    id: 'INC-2026-01',
    category: 'incident',
    title: 'LLaMA Batch Thermal Spike',
    summary: 'Synthetic historical incident: a LLaMA-3 batch workload drove the reference cluster to 84.2°C under reactive PID...',
    content: 'Synthetic historical incident: a LLaMA-3 batch workload drove the reference cluster to 84.2°C under reactive PID control, with 7 recorded throttle events. The corresponding NeuralFlow simulation held the peak near 71°C with 0 throttle events.',
    keywords: ['llama-3', '84.2c', '71c', 'pid', 'throttle', 'llama', 'batch', 'thermal', 'spike', 'inc'],
    tags: ['llama-3', '84.2c', '71c', 'pid', 'throttle', 'incident'],
  },
  {
    id: 'INC-2026-02',
    category: 'incident',
    title: 'GPU-04 Hotspot During API Surge',
    summary: 'Synthetic historical incident: API traffic rose rapidly while most GPUs remained near baseline.',
    content: 'Synthetic historical incident: API traffic rose rapidly while most GPUs remained near baseline. GPU-04 became the hottest node because workload placement and airflow were uneven. Corrective action was workload redistribution plus targeted cooling.',
    keywords: ['gpu-04', 'api', 'hotspot', 'redistribution', 'gpu', 'during', 'surge', 'inc', '2026', '02'],
    tags: ['gpu-04', 'api', 'hotspot', 'redistribution', 'incident'],
  },
  {
    id: 'INC-2026-03',
    category: 'incident',
    title: 'PID Oscillation After Burst',
    summary: 'Synthetic historical incident: reactive PID repeatedly raised and lowered fan speed after a short burst.',
    content: 'Synthetic historical incident: reactive PID repeatedly raised and lowered fan speed after a short burst. Temperature was safe, but fan actuation oscillated and consumed unnecessary energy. The lesson was to account for thermal lag before changing control gain.',
    keywords: ['pid', 'oscillation', 'fan', 'energy', 'after', 'burst', 'inc', '2026', '03', 'synthetic'],
    tags: ['pid', 'oscillation', 'fan', 'energy', 'incident'],
  },
  {
    id: 'INC-2026-04',
    category: 'incident',
    title: 'Late Fan Ramp',
    summary: 'Synthetic historical incident: workload power increased rapidly while fan speed stayed near baseline until measured...',
    content: 'Synthetic historical incident: workload power increased rapidly while fan speed stayed near baseline until measured temperature rose sharply. The control team concluded that waiting for a sensor threshold left too little thermal headroom.',
    keywords: ['fan ramp', 'sensor lag', 'headroom', 'late', 'fan', 'ramp', 'inc', '2026', '04', 'synthetic'],
    tags: ['fan ramp', 'sensor lag', 'headroom', 'incident'],
  },
  {
    id: 'INC-2026-05',
    category: 'incident',
    title: 'False Hotspot Signal',
    summary: 'Synthetic historical incident: one telemetry channel briefly reported a temperature spike that neighboring sensors did...',
    content: 'Synthetic historical incident: one telemetry channel briefly reported a temperature spike that neighboring sensors did not confirm. The system avoided an aggressive cluster-wide response by checking the broader telemetry pattern first.',
    keywords: ['sensor', 'false positive', 'telemetry', 'false', 'hotspot', 'signal', 'inc', '2026', '05', 'synthetic'],
    tags: ['sensor', 'false positive', 'telemetry', 'incident'],
  },
  {
    id: 'INC-2026-06',
    category: 'incident',
    title: 'Overcooling During Stable Load',
    summary: 'Synthetic historical incident: fan speed remained high after workload stabilized because the controller responded to an...',
    content: 'Synthetic historical incident: fan speed remained high after workload stabilized because the controller responded to an earlier spike. Energy use rose without meaningful temperature benefit. Remediation was gradual recovery logic.',
    keywords: ['overcooling', 'recovery', 'energy', 'during', 'stable', 'load', 'inc', '2026', '06', 'synthetic'],
    tags: ['overcooling', 'recovery', 'energy', 'incident'],
  },
  {
    id: 'INC-2026-07',
    category: 'incident',
    title: 'Workload Shift Prevented Cluster Escalation',
    summary: 'Synthetic historical incident: moving part of a hot GPU workload to cooler perimeter nodes reduced local thermal...',
    content: 'Synthetic historical incident: moving part of a hot GPU workload to cooler perimeter nodes reduced local thermal gradient without requiring all fans to run at maximum speed.',
    keywords: ['workload shift', 'perimeter', 'thermal gradient', 'workload', 'shift', 'prevented', 'cluster', 'escalation', 'inc', '2026'],
    tags: ['workload shift', 'perimeter', 'thermal gradient', 'incident'],
  },
  {
    id: 'INC-2026-08-PREDICTIVE',
    category: 'incident',
    title: 'Predictive Intervention Before Threshold',
    summary: 'Synthetic historical incident: NeuralFlow increased cooling after the forecast began trending upward even though...',
    content: 'Synthetic historical incident: NeuralFlow increased cooling after the forecast began trending upward even though current temperature was below the pre-cool threshold. The early response preserved more thermal headroom than the reactive baseline.',
    keywords: ['forecast', 'pre-cool', 'headroom', 'predictive', 'intervention', 'before', 'threshold', 'inc', '2026', '08'],
    tags: ['forecast', 'pre-cool', 'headroom', 'incident'],
  },
  {
    id: 'INC-2026-09',
    category: 'incident',
    title: 'Emergency Forecast Override',
    summary: 'Synthetic historical incident: a sustained workload produced a forecast above the emergency override level.',
    content: 'Synthetic historical incident: a sustained workload produced a forecast above the emergency override level. Protection logic escalated cooling before measured temperature reached the same value, preventing a projected throttle event in simulation.',
    keywords: ['forecast', 'override', 'throttle', 'emergency', 'inc', '2026', '09', 'synthetic', 'historical', 'incident'],
    tags: ['forecast', 'override', 'throttle', 'incident'],
  },
  {
    id: 'INC-2026-10',
    category: 'incident',
    title: 'Recovery Ramp Too Fast',
    summary: 'Synthetic historical incident: fans were reduced too quickly after a workload drop, and stored heat caused a secondary...',
    content: 'Synthetic historical incident: fans were reduced too quickly after a workload drop, and stored heat caused a secondary temperature rise. The recovery runbook was updated to step fans down more slowly.',
    keywords: ['recovery', 'thermal rebound', 'fan', 'ramp', 'too', 'fast', 'inc', '2026', '10', 'synthetic'],
    tags: ['recovery', 'thermal rebound', 'fan', 'incident'],
  },
  {
    id: 'INC-2026-11',
    category: 'incident',
    title: 'Cooling Saved Energy During Stable Period',
    summary: 'Synthetic historical incident: after the forecast returned to a stable low-risk state, fan speed was reduced gradually.',
    content: 'Synthetic historical incident: after the forecast returned to a stable low-risk state, fan speed was reduced gradually. The reference simulation maintained the safety margin while reducing fan power versus holding fans near maximum.',
    keywords: ['energy', 'stable', 'fan', 'cooling', 'saved', 'during', 'period', 'inc', '2026', '11'],
    tags: ['energy', 'stable', 'fan', 'incident'],
  },
  {
    id: 'INC-2026-12',
    category: 'incident',
    title: 'Cluster Balance During Mixed Workload',
    summary: 'Synthetic historical incident: AI and API workloads were distributed unevenly across the rack, creating a temperature...',
    content: 'Synthetic historical incident: AI and API workloads were distributed unevenly across the rack, creating a temperature difference between nodes. Rebalancing reduced the spread and improved cluster-wide thermal stability.',
    keywords: ['mixed workload', 'cluster balance', 'temperature spread', 'cluster', 'balance', 'during', 'mixed', 'workload', 'inc', '2026'],
    tags: ['mixed workload', 'cluster balance', 'temperature spread', 'incident'],
  },
  {
    id: 'INC-2026-13',
    category: 'incident',
    title: 'Voice Command Guardrail Test',
    summary: 'Synthetic test incident: an operator voice request attempted to push fan control outside the permitted range.',
    content: 'Synthetic test incident: an operator voice request attempted to push fan control outside the permitted range. The safety layer clamped the request and retained emergency protections.',
    keywords: ['voice', 'guardrail', 'fan', 'command', 'test', 'inc', '2026', '13', 'synthetic', 'incident'],
    tags: ['voice', 'guardrail', 'fan', 'incident'],
  },
  {
    id: 'INC-2026-14',
    category: 'incident',
    title: 'Retrieval-Grounded Intervention Review',
    summary: 'Synthetic review incident: an operator asked why a previous cooling action occurred.',
    content: 'Synthetic review incident: an operator asked why a previous cooling action occurred. Retrieval surfaced the relevant runbook and incident context, allowing the LLM to explain the decision without changing simulator state.',
    keywords: ['retrieval', 'runbook', 'audit', 'explanation', 'grounded', 'intervention', 'review', 'inc', '2026', '14'],
    tags: ['retrieval', 'runbook', 'audit', 'explanation', 'incident'],
  },
  {
    id: 'SIM-01-BURST-PROFILE',
    category: 'telemetry',
    title: 'Reference Burst Workload',
    summary: 'Synthetic simulation profile: workload rises from a stable baseline into a high-demand burst, power increases with...',
    content: 'Synthetic simulation profile: workload rises from a stable baseline into a high-demand burst, power increases with load, and temperature responds after a physical delay. The scenario tests whether proactive cooling starts early enough.',
    keywords: ['burst', 'power', 'temperature', 'delay', 'reference', 'workload', 'sim', '01', 'profile', 'synthetic'],
    tags: ['burst', 'power', 'temperature', 'delay', 'telemetry'],
  },
  {
    id: 'SIM-02-RISING-FORECAST',
    category: 'telemetry',
    title: 'Rising Forecast Scenario',
    summary: 'Synthetic scenario: current temperature remains below the danger zone while the 60-second forecast trends upward.',
    content: 'Synthetic scenario: current temperature remains below the danger zone while the 60-second forecast trends upward. Desired behavior is early intervention instead of waiting for the current value to cross the limit.',
    keywords: ['forecast', '60s', 'early intervention', 'rising', 'scenario', 'sim', '02', 'synthetic', 'current', 'temperature'],
    tags: ['forecast', '60s', 'early intervention', 'telemetry'],
  },
  {
    id: 'SIM-03-HOT-GPU',
    category: 'telemetry',
    title: 'Single-GPU Hotspot Scenario',
    summary: 'Synthetic scenario: GPU-04 receives a disproportionate workload share while neighbors remain cooler.',
    content: 'Synthetic scenario: GPU-04 receives a disproportionate workload share while neighbors remain cooler. The test evaluates workload redistribution and localized cooling.',
    keywords: ['gpu-04', 'hotspot', 'redistribution', 'single', 'gpu', 'scenario', 'sim', '03', 'hot', 'synthetic'],
    tags: ['gpu-04', 'hotspot', 'redistribution', 'telemetry'],
  },
  {
    id: 'SIM-04-RECOVERY',
    category: 'telemetry',
    title: 'Cooling Recovery Scenario',
    summary: 'Synthetic scenario: workload falls sharply after a burst.',
    content: 'Synthetic scenario: workload falls sharply after a burst. Correct response is controlled fan recovery followed by verification that temperature continues declining.',
    keywords: ['recovery', 'fan', 'workload drop', 'cooling', 'scenario', 'sim', '04', 'synthetic', 'workload', 'falls'],
    tags: ['recovery', 'fan', 'workload drop', 'telemetry'],
  },
  {
    id: 'SIM-05-PID-BASELINE',
    category: 'telemetry',
    title: 'Reactive PID Baseline Scenario',
    summary: 'Synthetic baseline scenario: PID reacts to measured temperature after the rise is visible.',
    content: 'Synthetic baseline scenario: PID reacts to measured temperature after the rise is visible. Comparison evaluates overshoot, throttle events, and energy use rather than final temperature alone.',
    keywords: ['pid', 'baseline', 'overshoot', 'reactive', 'scenario', 'sim', '05', 'synthetic', 'reacts', 'measured'],
    tags: ['pid', 'baseline', 'overshoot', 'telemetry'],
  },
  {
    id: 'SIM-06-NF-PREDICTIVE',
    category: 'telemetry',
    title: 'NeuralFlow Predictive Scenario',
    summary: 'Synthetic scenario: controller uses forecast trajectory to begin cooling before measured temperature reaches a critical...',
    content: 'Synthetic scenario: controller uses forecast trajectory to begin cooling before measured temperature reaches a critical band. Expected benefit is more thermal headroom and fewer emergency interventions.',
    keywords: ['neuralflow', 'predictive', 'headroom', 'scenario', 'sim', '06', 'nf', 'synthetic', 'controller', 'uses'],
    tags: ['neuralflow', 'predictive', 'headroom', 'telemetry'],
  },
  {
    id: 'SIM-07-LOAD-STEP',
    category: 'telemetry',
    title: 'Workload Step Test',
    summary: 'Synthetic step test: workload changes abruptly from moderate to high.',
    content: 'Synthetic step test: workload changes abruptly from moderate to high. Evaluate reaction time, fan ramp, peak temperature, and recovery between controllers.',
    keywords: ['workload step', 'fan ramp', 'comparison', 'workload', 'step', 'test', 'sim', '07', 'load', 'synthetic'],
    tags: ['workload step', 'fan ramp', 'comparison', 'telemetry'],
  },
  {
    id: 'SIM-08-UNCERTAINTY',
    category: 'telemetry',
    title: 'Forecast Uncertainty Scenario',
    summary: 'Synthetic scenario: predicted temperature rises while uncertainty is high.',
    content: 'Synthetic scenario: predicted temperature rises while uncertainty is high. Test whether the system uses supporting telemetry and avoids unstable repeated control changes.',
    keywords: ['uncertainty', 'forecast', 'control', 'scenario', 'sim', '08', 'synthetic', 'predicted', 'temperature', 'rises'],
    tags: ['uncertainty', 'forecast', 'control', 'telemetry'],
  },
  {
    id: 'REF-22-PREDICTIVE-CONTROL',
    category: 'reference',
    title: 'Predictive Control Principle',
    summary: 'NeuralFlow treats future temperature as a control signal rather than waiting for the current sensor value to become...',
    content: 'NeuralFlow treats future temperature as a control signal rather than waiting for the current sensor value to become unsafe. This shifts cooling from reactive correction toward proactive intervention.',
    keywords: ['predictive control', 'future temperature', 'proactive', 'predictive', 'control', 'principle', 'ref', '22', 'neuralflow', 'treats'],
    tags: ['predictive control', 'future temperature', 'proactive', 'reference'],
  },
  {
    id: 'REF-23-THERMAL-MARGIN',
    category: 'reference',
    title: 'Thermal Margin',
    summary: 'Thermal margin is the remaining space between current or forecast temperature and the next protective threshold.',
    content: 'Thermal margin is the remaining space between current or forecast temperature and the next protective threshold. Preserving margin gives the controller more time to respond before throttling becomes unavoidable.',
    keywords: ['thermal margin', 'headroom', 'thermal', 'margin', 'ref', '23', 'remaining', 'space', 'between', 'current'],
    tags: ['thermal margin', 'headroom', 'reference'],
  },
  {
    id: 'REF-24-REACTIVE-LAG',
    category: 'reference',
    title: 'Why Reactive Cooling Lags',
    summary: 'Reactive cooling waits for visible temperature response before changing control.',
    content: 'Reactive cooling waits for visible temperature response before changing control. Silicon, heatsinks, sensors, and actuators introduce delays, so the sequence can arrive after the thermal trajectory is already difficult to reverse.',
    keywords: ['reactive', 'lag', 'sensor', 'actuator', 'why', 'cooling', 'lags', 'ref', '24', 'waits'],
    tags: ['reactive', 'lag', 'sensor', 'actuator', 'reference'],
  },
  {
    id: 'REF-25-FAN-ENERGY',
    category: 'reference',
    title: 'Fan Energy Scaling',
    summary: 'The reference model emphasizes that fan energy rises steeply with fan speed.',
    content: 'The reference model emphasizes that fan energy rises steeply with fan speed. Maintaining moderate proactive cooling can be preferable to repeatedly jumping to maximum speed after a thermal spike.',
    keywords: ['fan energy', 'cube law', 'efficiency', 'fan', 'energy', 'scaling', 'ref', '25', 'reference', 'model'],
    tags: ['fan energy', 'cube law', 'efficiency', 'reference'],
  },
  {
    id: 'REF-26-CLUSTER-VS-LOCAL',
    category: 'reference',
    title: 'Cluster Control vs Local Control',
    summary: 'A local temperature problem can sometimes be solved by moving workload rather than increasing every fan.',
    content: 'A local temperature problem can sometimes be solved by moving workload rather than increasing every fan. NeuralFlow considers both spatial placement and thermal control when one GPU becomes a hotspot.',
    keywords: ['cluster control', 'local control', 'workload placement', 'cluster', 'control', 'local', 'ref', '26', 'vs', 'temperature'],
    tags: ['cluster control', 'local control', 'workload placement', 'reference'],
  },
  {
    id: 'REF-27-MULTI-SIGNAL',
    category: 'reference',
    title: 'Multi-Signal Thermal Reasoning',
    summary: 'Reliable intervention should consider temperature, temperature trend, predicted temperature, workload, fan speed, and...',
    content: 'Reliable intervention should consider temperature, temperature trend, predicted temperature, workload, fan speed, and power together. A single signal can be noisy or misleading.',
    keywords: ['telemetry', 'trend', 'forecast', 'power', 'multi', 'signal', 'thermal', 'reasoning', 'ref', '27'],
    tags: ['telemetry', 'trend', 'forecast', 'power', 'reference'],
  },
  {
    id: 'REF-28-INCIDENT-MEMORY',
    category: 'reference',
    title: 'Using Historical Incidents',
    summary: 'Historical incidents provide precedent for deciding how similar thermal patterns were handled.',
    content: 'Historical incidents provide precedent for deciding how similar thermal patterns were handled. Retrieval is useful for prior cases, lessons, and rationale behind control actions.',
    keywords: ['history', 'incidents', 'retrieval', 'precedent', 'using', 'historical', 'ref', '28', 'incident', 'memory'],
    tags: ['history', 'incidents', 'retrieval', 'precedent', 'reference'],
  },
  {
    id: 'REF-29-SEMANTIC-RETRIEVAL',
    category: 'reference',
    title: 'Why Semantic Retrieval Matters',
    summary: 'An operator may describe the same concept using different words than the source document.',
    content: 'An operator may describe the same concept using different words than the source document. Semantic retrieval can connect paraphrased questions to related runbooks, incidents, and engineering notes.',
    keywords: ['semantic retrieval', 'paraphrase', 'moss', 'why', 'semantic', 'retrieval', 'matters', 'ref', '29', 'operator'],
    tags: ['semantic retrieval', 'paraphrase', 'moss', 'reference'],
  },
  {
    id: 'REF-30-KEYWORD-LIMIT',
    category: 'reference',
    title: 'Local Keyword Retrieval Limitation',
    summary: 'Keyword retrieval is strongest when the query shares vocabulary with indexed text.',
    content: 'Keyword retrieval is strongest when the query shares vocabulary with indexed text. It can work well for obvious queries, but is less robust when wording is unfamiliar or combines several related concepts.',
    keywords: ['keyword', 'local fallback', 'retrieval', 'local', 'limitation', 'ref', '30', 'limit', 'strongest', 'query'],
    tags: ['keyword', 'local fallback', 'retrieval', 'reference'],
  },
  {
    id: 'REF-31-RETRIEVAL-PROVENANCE',
    category: 'reference',
    title: 'Retrieval Provenance',
    summary: 'A retrieval result should expose backend, latency, matched document identifiers, and relevance information so an...',
    content: 'A retrieval result should expose backend, latency, matched document identifiers, and relevance information so an operator can distinguish a retrieved fact from a generic model response.',
    keywords: ['provenance', 'latency', 'documents', 'retrieval', 'ref', '31', 'result', 'expose', 'backend', 'matched'],
    tags: ['provenance', 'latency', 'documents', 'reference'],
  },
  {
    id: 'REF-32-VOICE-GROUNDING',
    category: 'reference',
    title: 'Voice Grounding Principle',
    summary: 'For spoken operations questions, the LLM should answer from retrieved NeuralFlow context when a matching document exists.',
    content: 'For spoken operations questions, the LLM should answer from retrieved NeuralFlow context when a matching document exists. This keeps explanations aligned with actual project runbooks and incidents.',
    keywords: ['voice', 'grounding', 'llm', 'retrieval', 'principle', 'ref', '32', 'spoken', 'operations', 'questions'],
    tags: ['voice', 'grounding', 'llm', 'retrieval', 'reference'],
  },
  {
    id: 'REF-33-ACTION-VS-KNOWLEDGE',
    category: 'reference',
    title: 'Knowledge vs Action Intent',
    summary: 'Questions such as why, when, what, and how should the system should be treated as informational unless the user...',
    content: 'Questions such as why, when, what, and how should the system should be treated as informational unless the user explicitly requests an operational command. Workload-related words alone are not sufficient evidence of an action.',
    keywords: ['intent', 'knowledge', 'action', 'voice', 'ref', '33', 'vs', 'questions', 'such', 'system'],
    tags: ['intent', 'knowledge', 'action', 'voice', 'reference'],
  },
];
